server:
  port: 8077

jaeger:
  host: http://10.152.183.235:14250

logging:
  pattern:
    console: "%d [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: INFO
    org.springframework: INFO
    root: INFO
temporal:
    host: localhost
    port: 30715
    namespace: demo
grpc-service:
  host: localhost
  port: 50051
sink-service:
  host: localhost
  port: 8099
spring:
  application:
    name: "temporal-worker"