server:
  port: 8077

jaeger:
  host: http://localhost:32473

logging:
  pattern:
    console: "%d [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO
temporal:
    host: localhost
    port: 30715
    namespace: demo
grpc-service:
  host: localhost
  port: 50051
spring:
  application:
    name: "temporal-worker"