server:
  port: 8099

logging:
  pattern:
    console: "%d [%X{traceId}/%X{parentId}/%X{spanId}/%X{sampled}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO

spring:
  application:
    name: "temporal-sink-service"
  zipkin:
    base-url: "http://localhost:31941"
  sleuth:
    sampler:
      rate: 50
    trace-id128: false
