server:
  port: 8099

logging:
  pattern:
    console: "%d [%X{trace_id}/%X{span_id}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO

spring:
  application:
    name: "temporal-sink-service"
