grpc:
  port : 50051

logging:
  pattern:
    console: "%d [%X{trace_id}/%X{span_id}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO

## default connection pool
spring:
  application:
    name: tempora-demo-grpc-service

