grpc:
  port : 50051

logging:
  pattern:
    console: "%d [%X{traceId}/%X{parentId}/%X{spanId}/%X{sampled}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO

## default connection pool
spring:
  application:
    name: hello-service
  zipkin:
    base-url: "http://localhost:31941"
  sleuth:
    sampler:
      rate: 50
    trace-id128: false

