server:
  port: 8066

logging:
  pattern:
    console: "%d [%X{trace_id}/%X{span_id}] [%thread] %-5level %logger{36} - %m%n"
  level:
    com.github.balchua: DEBUG
    org.springframework: INFO
    root: INFO
jaeger:
  host: http://localhost:32473
temporal:
  host: localhost
  port: 30715
  namespace: demo

spring:
  application:
    name: "temporal-starter"
